const cards=[
 {name:'Paladin du Royaume',faction:'ORDRE',cost:2,power:4,art:'♜',text:'Frappe avec la force du serment.'},
 {name:'Loup Alpha',faction:'MEUTE',cost:1,power:3,art:'◈',text:'Rapide et impossible à ignorer.'},
 {name:'Éclat de Nexus',faction:'ARCANE',cost:1,power:2,art:'✧',text:'Une étincelle d’Évosphère.'},
 {name:'Veilleur des Brumes',faction:'OMBRE',cost:3,power:6,art:'☽',text:'Les brumes cachent sa charge.'},
 {name:'Oracle de Verre',faction:'ARCANE',cost:2,power:4,art:'◉',text:'Voit le prochain mouvement.'},
 {name:'Aube Souveraine',faction:'ORDRE',cost:3,power:5,art:'☀',text:'La lumière répond au courage.'}
];
const chapters=['Le serment brisé','La route des crocs','La forêt de verre','Les cendres de Sélène','La tour oubliée','Le palais sous la brume','La Reine effacée'];
let state=JSON.parse(localStorage.getItem('nexus-state')||'{"wins":0,"chapter":0,"sound":false}');
let duel;
const $=id=>document.getElementById(id);
function save(){localStorage.setItem('nexus-state',JSON.stringify(state));$('winsLabel').textContent=`${state.wins} victoire${state.wins!==1?'s':''}`;$('campaignStatus').textContent=`${state.chapter} / 7 chapitres terminés`}
function show(name){document.querySelectorAll('.screen').forEach(s=>s.classList.add('hidden'));$(name+'Screen').classList.remove('hidden');if(name==='campaign')renderCampaign();if(name==='collection')renderCollection();}
function renderCampaign(){$('chapters').innerHTML=chapters.map((title,i)=>`<article class="chapter ${i>state.chapter?'locked':''}"><span class="number">0${i+1}</span><div class="chapter-body"><b>${title}</b><small>${i<state.chapter?'Victoire inscrite dans les archives':i===state.chapter?'Gardien à affronter':'Scellé par la Reine'}</small></div>${i<=state.chapter?`<button data-chapter="${i}">${i<state.chapter?'Rejouer':'Jouer'}</button>`:'<span>◌</span>'}</article>`).join('');document.querySelectorAll('[data-chapter]').forEach(b=>b.onclick=()=>startDuel(+b.dataset.chapter));}
function renderCollection(){$('collection').innerHTML=cards.map(c=>`<article class="archive-card"><span class="glyph">${c.art}</span><h3>${c.name}</h3><p>${c.faction} · Puissance ${c.power}</p></article>`).join('')}
function shuffled(){return [...cards].sort(()=>Math.random()-.5)}
function startDuel(chapter=0){duel={chapter,player:20,enemy:18+chapter*2,energy:3,maxEnergy:3,round:1,hand:shuffled().slice(0,3),enemyHand:3,ended:false};show('duel');renderDuel('Le duel commence. Choisis une carte.');}
function renderDuel(message){$('playerHealth').textContent=duel.player;$('enemyHealth').textContent=duel.enemy;$('playerHealthBar').style.width=`${Math.max(0,duel.player)*5}%`;$('enemyHealthBar').style.width=`${Math.max(0,duel.enemy)/(18+duel.chapter*2)*100}%`;$('roundNumber').textContent=duel.round;$('energyNumber').textContent=`${duel.energy} / ${duel.maxEnergy}`;$('energyPips').innerHTML=Array.from({length:duel.maxEnergy},(_,i)=>`<i class="pip ${i<duel.energy?'filled':''}"></i>`).join('');$('enemyHand').innerHTML=Array.from({length:duel.enemyHand},()=>'<i class="enemy-card"></i>').join('');$('battleLog').textContent=message;$('turnLabel').textContent=duel.ended?'DUEL TERMINÉ':'TON TOUR';const hand=$('playerHand');hand.innerHTML='';duel.hand.forEach((card,i)=>{const el=$('cardTemplate').content.firstElementChild.cloneNode(true);el.querySelector('.card-faction').textContent=card.faction;el.querySelector('.card-name').textContent=card.name;el.querySelector('.card-art').textContent=card.art;el.querySelector('.card-text').textContent=card.text;el.querySelector('.card-cost').textContent=card.cost;el.querySelector('.card-power').textContent=card.power;el.disabled=duel.ended||card.cost>duel.energy;el.onclick=()=>playCard(i);hand.append(el)});$('endTurn').disabled=duel.ended;$('endTurn').textContent=duel.ended?'Retour à la campagne':'Terminer le tour →';}
function playCard(index){const card=duel.hand[index];if(card.cost>duel.energy||duel.ended)return;duel.energy-=card.cost;duel.enemy-=card.power;duel.hand.splice(index,1);if(duel.enemy<=0)return victory(`${card.name} inflige ${card.power} dégâts. La Sentinelle tombe.`);renderDuel(`${card.name} traverse les défenses : ${card.power} dégâts.`)}
function enemyTurn(){const hit=2+Math.floor(Math.random()*4)+duel.chapter;duel.player-=hit;if(duel.player<=0){duel.ended=true;renderDuel(`La Sentinelle inflige ${hit} dégâts. Chronos est vaincu — retente ta chance.`);$('endTurn').onclick=()=>startDuel(duel.chapter);return}duel.round++;duel.maxEnergy=Math.min(6,duel.maxEnergy+1);duel.energy=duel.maxEnergy;duel.hand.push(shuffled()[0]);duel.enemyHand=Math.min(5,duel.enemyHand+1);renderDuel(`La Sentinelle riposte : ${hit} dégâts. Une nouvelle carte rejoint ta main.`)}
function victory(text){duel.ended=true;if(duel.chapter===state.chapter&&state.chapter<7)state.chapter++;state.wins++;save();renderDuel(text+' Victoire !');$('endTurn').onclick=()=>show('campaign')}
document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{const a=b.dataset.action;if(a==='home')show('home');else if(a==='duel')startDuel();else show(a)});$('endTurn').onclick=()=>enemyTurn();$('soundButton').onclick=()=>{state.sound=!state.sound;$('soundButton').textContent=state.sound?'♫':'♬';save()};save();
