import { CardDef, EffectDef, Faction, Rarity } from './types';
import { assertValidCardDatabase } from './card-validation';

function rarityForCost(cost: number): Rarity { if (cost <= 1) return 'Commune'; if (cost === 2) return 'Rare'; if (cost === 3) return 'Épique'; return 'Légendaire'; }
type Row = [string, string, number, number, number, EffectDef | undefined, boolean?];
const wolfRows: Row[] = [
['louve-veilleuse','Louve Veilleuse',1,2,3,{kind:'protect'}],['loup-eclaireur','Loup Éclaireur',1,2,2,{kind:'search',target:'Meute'}],['jeune-croc','Jeune Croc',1,3,1,undefined],['loup-des-brumes','Loup des Brumes',2,3,3,{kind:'stun',value:1}],['chasseuse-grise','Chasseuse Grise',2,3,4,undefined],['loup-de-givre','Loup de Givre',2,2,5,{kind:'stun',value:1}],['pisteur-alpha','Pisteur Alpha',3,5,3,{kind:'draw',value:1}],['loup-sentinelle','Loup Sentinelle',3,4,5,{kind:'protect'}],['hurleur-de-nuit','Hurleur de Nuit',3,5,4,{kind:'buff',value:1}],['croc-de-fer','Croc de Fer',4,6,5,undefined],['meute-rassemblee','Meute Rassemblée',2,0,0,{kind:'summon',target:'Meute'}],['appel-de-la-lune','Appel de la Lune',2,0,0,{kind:'search',target:'Meute'}],['instinct-de-survie','Instinct de Survie',1,0,0,{kind:'protect'}],['morsure-sauvage','Morsure Sauvage',2,0,0,{kind:'damage',value:3}],['territoire-sacre','Territoire Sacré',3,0,0,{kind:'buff',value:1}],['emprise-de-la-meute','Emprise de la Meute',3,0,0,{kind:'stun',value:1}],['lune-rouge','Lune Rouge',4,0,0,{kind:'buff',value:2}],['totem-alpha','Totem Alpha',2,0,4,{kind:'buff',value:1}],['pacte-des-crocs','Pacte des Crocs',1,0,0,{kind:'draw',value:1}],['derniere-trace','Dernière Trace',2,0,0,{kind:'search',target:'Meute'}],['eclaireuse-des-crocs','Éclaireuse des Crocs',1,2,2,{kind:'draw',value:1},true],['chasseuse-des-ombres','Chasseuse des Ombres',2,3,2,{kind:'protect'},true],['meute-enragee','Meute Enragée',3,4,2,{kind:'buff',value:2},true],['piege-de-givre','Piège de Givre',1,0,0,{kind:'stun',value:2},true],['sang-pour-sang','Sang pour Sang',3,0,0,{kind:'damage',value:5},true],['rugissement-de-la-meute','Rugissement de la Meute',4,0,0,{kind:'summon',target:'Meute'},true]];
const knightRows: Row[] = [
['ecuyer-dore','Écuyer Doré',1,1,4,{kind:'protect'}],['novice-du-serment','Novice du Serment',1,2,3,{kind:'search',target:'Chevalier'}],['lame-blanche','Lame Blanche',1,3,2,undefined],['garde-du-portail','Garde du Portail',2,3,5,{kind:'protect'}],['paladin-des-cendres','Paladin des Cendres',2,4,3,undefined],['chevalier-azur','Chevalier Azur',2,3,4,{kind:'stun',value:1}],['porte-etendard','Porte-Étendard',3,3,5,{kind:'buff',value:1}],['sentinelle-doree','Sentinelle Dorée',3,4,6,{kind:'protect'}],['duelliste-royal','Duelliste Royal',3,5,3,undefined],['capitaine-du-royaume','Capitaine du Royaume',4,6,5,{kind:'draw',value:1}],['ordre-de-ralliement','Ordre de Ralliement',2,0,0,{kind:'summon',target:'Chevalier'}],['grande-bibliotheque','Grande Bibliothèque',2,0,0,{kind:'search',target:'Chevalier'}],['bouclier-de-lumiere','Bouclier de Lumière',1,0,0,{kind:'protect'}],['jugement-solaire','Jugement Solaire',2,0,0,{kind:'damage',value:3}],['banniere-du-royaume','Bannière du Royaume',3,0,0,{kind:'buff',value:1}],['sceau-immobilite',"Sceau d'Immobilité",3,0,0,{kind:'stun',value:1}],['aube-victorieuse','Aube Victorieuse',4,0,0,{kind:'buff',value:2}],['reliquaire-du-roi','Reliquaire du Roi',2,0,4,{kind:'buff',value:1}],['serment-de-garde','Serment de Garde',1,0,0,{kind:'draw',value:1}],['voie-du-paladin','Voie du Paladin',2,0,0,{kind:'search',target:'Chevalier'}],['recrue-du-serment','Recrue du Serment',1,1,3,{kind:'protect'},true],['bibliothecaire-royale','Bibliothécaire Royale',2,2,3,{kind:'draw',value:1},true],['veteran-des-remparts','Vétéran des Remparts',3,3,6,{kind:'protect'},true],['serment-inebranlable','Serment Inébranlable',1,0,0,{kind:'stun',value:2},true],['lumiere-purificatrice','Lumière Purificatrice',2,0,0,{kind:'damage',value:4},true],['renfort-du-royaume','Renfort du Royaume',5,0,0,{kind:'summon',target:'Chevalier'},true]];
const orcRows: Row[] = [
['brute-des-tourbieres','Brute des Tourbières',1,2,3,{kind:'protect'}],['eclaireur-vert-de-gris','Éclaireur Vert-de-Gris',1,2,2,{kind:'search',target:'Orc'}],['jeune-massacreur','Jeune Massacreur',1,3,1,undefined],['guerrier-ecumant','Guerrier Écumant',2,3,3,{kind:'stun',value:1}],['chasseuse-de-cranes','Chasseuse de Crânes',2,3,4,undefined],['berserker-des-cendres','Berserker des Cendres',2,2,5,{kind:'stun',value:1}],['chaman-de-guerre','Chaman de Guerre',3,5,3,{kind:'draw',value:1}],['garde-sanglant','Garde Sanglant',3,4,5,{kind:'protect'}],['hurleur-de-guerre','Hurleur de Guerre',3,5,4,{kind:'buff',value:1}],['chef-de-guerre','Chef de Guerre',4,6,5,undefined],['ralliement-du-clan','Ralliement du Clan',2,0,0,{kind:'summon',target:'Orc'}],['appel-des-tambours','Appel des Tambours',2,0,0,{kind:'search',target:'Orc'}],['instinct-brutal','Instinct Brutal',1,0,0,{kind:'protect'}],['coup-de-hache','Coup de Hache',2,0,0,{kind:'damage',value:3}],['terre-de-sang','Terre de Sang',3,0,0,{kind:'buff',value:1}],['joug-du-clan','Joug du Clan',3,0,0,{kind:'stun',value:1}],['lune-sanglante','Lune Sanglante',4,0,0,{kind:'buff',value:2}],['totem-de-guerre','Totem de Guerre',2,0,4,{kind:'buff',value:1}],['pacte-du-sang','Pacte du Sang',1,0,0,{kind:'draw',value:1}],['derniere-charge','Dernière Charge',2,0,0,{kind:'search',target:'Orc'}],['eclaireuse-des-cendres','Éclaireuse des Cendres',1,2,2,{kind:'draw',value:1},true],['chasseuse-des-tourbieres','Chasseuse des Tourbières',2,3,2,{kind:'protect'},true],['horde-dechainee','Horde Déchaînée',3,4,2,{kind:'buff',value:2},true],['piege-a-ours','Piège à Ours',1,0,0,{kind:'stun',value:2},true],['rage-sanguinaire','Rage Sanguinaire',3,0,0,{kind:'damage',value:5},true],['cri-de-guerre-orc','Cri de Guerre Orc',4,0,0,{kind:'summon',target:'Orc'},true]];
const dragonRows: Row[] = [
['dragonnet-de-cendre','Dragonnet de Cendre',1,2,2,undefined],['dragonnet-des-rocs','Dragonnet des Rocs',1,1,3,undefined],['wyverne-du-brasier','Wyverne du Brasier',2,4,3,{kind:'damage',value:2}],['drake-ecaille-de-fer','Drake Écaille-de-Fer',2,3,5,{kind:'protect'}],['dragon-de-givre','Dragon de Givre',3,5,5,{kind:'stun',value:1}],['dragon-des-tempetes','Dragon des Tempêtes',3,5,4,{kind:'draw',value:1}],['dragon-de-fer','Dragon de Fer',3,4,7,{kind:'protect'}],['dragon-solaire','Dragon Solaire',4,7,5,{kind:'damage',value:3}],['dragon-abyssal','Dragon Abyssal',4,6,7,{kind:'buff',value:1}],['dragon-ancien','Dragon Ancien',5,8,8,{kind:'draw',value:1}],['appel-des-ecailles','Appel des Écailles',2,0,0,{kind:'summon',target:'Dragon'}],['tresor-draconique','Trésor Draconique',2,0,0,{kind:'search',target:'Dragon'}],['ecaille-ancestrale','Écaille Ancestrale',1,0,0,{kind:'protect'}],['souffle-de-feu','Souffle de Feu',2,0,0,{kind:'damage',value:3}],['hurlement-du-ciel','Hurlement du Ciel',3,0,0,{kind:'stun',value:1}],['sang-draconique','Sang Draconique',3,0,0,{kind:'buff',value:2}],['effondrement-draconique','Effondrement Draconique',4,0,0,{kind:'board_wipe'}],['oeuf-ancien','Œuf Ancien',2,0,0,{kind:'summon',target:'Dragon'}],['memoire-des-anciens','Mémoire des Anciens',1,0,0,{kind:'draw',value:1}],['appel-du-roi-dragon','Appel du Roi-Dragon',3,0,0,{kind:'search',target:'Dragon'}],['dragon-comete','Dragon Comète',3,6,4,{kind:'damage',value:2},true],['dragon-de-cristal','Dragon de Cristal',3,4,7,{kind:'stun',value:1},true],['tyran-des-cieux','Tyran des Cieux',5,9,7,{kind:'protect'},true],['pluie-de-meteores','Pluie de Météores',4,0,0,{kind:'damage',value:5},true],['ailes-du-destin','Ailes du Destin',2,0,0,{kind:'draw',value:2},true],['rugissement-primordial','Rugissement Primordial',5,0,0,{kind:'board_wipe'},true]];
const goblinRows: Row[] = [
['gobelin-au-couteau','Gobelin au Couteau',1,2,1,undefined],['gobelin-frondeur','Gobelin Frondeur',1,1,2,{kind:'damage',value:1}],['gobelin-pillard','Gobelin Pillard',1,2,1,{kind:'draw',value:1}],['gobelin-recruteur','Gobelin Recruteur',1,1,1,{kind:'summon',target:'Gobelin'}],['gobelin-a-la-bombe','Gobelin à la Bombe',1,3,1,{kind:'damage',value:1}],['gobelin-chaman','Gobelin Chaman',2,2,2,{kind:'draw',value:1}],['gobelin-chevaucheur','Gobelin Chevaucheur',2,3,2,{kind:'summon',target:'Gobelin'}],['gobelin-sapeur','Gobelin Sapeur',2,3,2,{kind:'damage',value:2}],['chef-gobelin','Chef Gobelin',3,4,3,{kind:'buff',value:1}],['roi-gobelin','Roi Gobelin',3,4,4,{kind:'summon',target:'Gobelin'}],['appel-de-la-horde','Appel de la Horde',1,0,0,{kind:'summon',target:'Gobelin'}],['butin-vole','Butin Volé',1,0,0,{kind:'draw',value:1}],['embuscade-sale','Embuscade Sale',1,0,0,{kind:'stun',value:1}],['coup-bas','Coup Bas',1,0,0,{kind:'damage',value:2}],['banniere-bancale','Bannière Bancale',2,0,0,{kind:'buff',value:1}],['plan-foireux','Plan Foireux',1,0,0,{kind:'draw',value:2}],['tunnel-secret','Tunnel Secret',2,0,0,{kind:'summon',target:'Gobelin'}],['piege-a-clous','Piège à Clous',2,0,0,{kind:'stun',value:1}],['poudre-noire','Poudre Noire',3,0,0,{kind:'damage',value:4}],['tout-pour-la-horde','Tout pour la Horde',3,0,0,{kind:'buff',value:2}],['gobelin-fusee','Gobelin-Fusée',1,2,1,{kind:'draw',value:1},true],['gobelin-alchimiste','Gobelin Alchimiste',2,2,2,{kind:'damage',value:2},true],['champion-de-la-decharge','Champion de la Décharge',3,4,3,{kind:'summon',target:'Gobelin'},true],['explosion-improvisee','Explosion Improvisée',3,0,0,{kind:'damage',value:5},true],['filet-de-ferraille','Filet de Ferraille',2,0,0,{kind:'stun',value:2},true],['maree-verte','Marée Verte',4,0,0,{kind:'summon',target:'Gobelin'},true]];
const evolutionNames: Partial<Record<Faction,string[]>> = {Meute:['Alpha des Brumes','Traqueur Lunaire','Croc du Premier Sang','Spectre de la Meute','Matriarche Grise','Fléau de Givre','Alpha Pisteur','Gardien du Territoire','Hurleur des Mille Lunes','Bête de Fer'],Chevalier:["Chevalier d'Or",'Paladin du Serment',"Lame de l'Aube",'Rempart Royal','Flamme du Royaume','Croisé Azur','Maréchal des Bannières','Gardien du Trône','Champion de la Couronne','Seigneur du Royaume'],Orc:['Brute Sanguinaire','Traqueur des Cendres','Massacreur Ivre de Sang','Guerrier Déchaîné','Collectionneuse de Crânes','Berserker Infernal','Grand Chaman de Guerre','Garde du Chef de Guerre','Hurleur des Enfers','Seigneur de Guerre']};
Object.assign(evolutionNames,{Dragon:['Drake de Cendre','Gardien des Montagnes','Wyverne Incendiaire','Drake Bastion','Fléau du Givre','Seigneur des Tempêtes','Colosse de Fer','Avatar Solaire','Léviathan Abyssal','Ancien Primordial'],Gobelin:['Surineur Frénétique','Maître Frondeur','Pillard Couronné','Grand Recruteur','Bombardier Fou','Grand Chaman Vert','Chevaucheur de Guerre','Maître Sapeur','Chef de la Horde','Roi de la Décharge']});
const REACTION_IDS=new Set(['piege-de-givre','serment-inebranlable','sceau-immobilite','piege-a-ours','embuscade-sale','piege-a-clous']);
const BLITZ_IDS=new Set(['loup-eclaireur','eclaireuse-des-crocs','eclaireur-vert-de-gris','eclaireuse-des-cendres']);
const RANGED_IDS=new Set(['chaman-de-guerre','gobelin-frondeur','gobelin-chaman']);
const PLANNED_FLYING_IDS=new Set(['wyverne-du-brasier','dragon-de-givre','dragon-des-tempetes','dragon-solaire','dragon-abyssal','dragon-ancien','dragon-comete','dragon-de-cristal','tyran-des-cieux']);
function buildFaction(faction:Faction,rows:Row[]):CardDef[]{
 const evolvableIds=new Set(rows.filter(([, , , ,h])=>h>0).slice(0,10).map(([id])=>id));
 const namesForFaction=evolutionNames[faction] ?? [];
 const evolutionNameById=new Map(rows.filter(([id])=>evolvableIds.has(id)).map(([id],i)=>[id,namesForFaction[i]]));
 const base:CardDef[]=rows.map(([id,name,cost,attack,health,effect,boosterOnly])=>{const nativeGoblinBlitz=faction==='Gobelin'&&health>0;const dragonDelay=faction==='Dragon'&&health>0&&cost>=2?2:undefined;const hasBlitz=BLITZ_IDS.has(id)||nativeGoblinBlitz;return {id,name,faction,level:1,type:health>0?'unit':'spell',supportKind:health<=0?(REACTION_IDS.has(id)?'reaction':'enchantment'):undefined,reactionTriggers:REACTION_IDS.has(id)?['attack_declared']:undefined,cost,attack,health,effect,blitz:hasBlitz||undefined,ranged:RANGED_IDS.has(id)||undefined,attackDelayTurns:dragonDelay,waitTurns:evolvableIds.has(id)?3:undefined,evolvesTo:evolvableIds.has(id)?`evo-${id}`:undefined,copies:3,rarity:rarityForCost(cost),image:`${import.meta.env.BASE_URL}cards/${id}.png`,text:describeEffect(effect)+(hasBlitz?' Blitz.':'')+(dragonDelay?' Inertie draconique : attend 2 tours avant de pouvoir attaquer.':'')+(RANGED_IDS.has(id)?' À distance.':'')+(evolvableIds.has(id)?` Évolue en ${evolutionNameById.get(id)}.`:''),boosterOnly:boosterOnly||undefined};});
 const evolvables=base.filter(c=>evolvableIds.has(c.id)); const names=evolutionNames[faction] ?? [];
 const evolutions:CardDef[]=evolvables.map((from,i)=>({id:`evo-${from.id}`,name:names[i],faction,level:2,type:'unit',cost:from.cost+1,attack:from.attack+2,health:from.health+2,effect:{kind:'buff',value:1},evolvesFrom:from.id,copies:3,rarity:'Légendaire',image:`${import.meta.env.BASE_URL}cards/evo-${from.id}.png`,text:`Évolution de ${from.name}. Cri de guerre : +1 attaque à une unité alliée.`}));
 return [...base,...evolutions];
}
function describeEffect(effect?:EffectDef):string{if(!effect)return'Aucun effet spécial.';switch(effect.kind){case'protect':return'Provocation : les ennemis doivent attaquer cette unité en priorité.';case'draw':return`Cri de guerre : pioche ${effect.value??1} carte(s).`;case'search':return`Cri de guerre : cherche une carte ${effect.target??''} dans le deck.`;case'stun':return`Étourdit une unité ennemie pendant ${effect.value??1} tour(s).`;case'damage':return`Inflige ${effect.value??0} dégâts.`;case'buff':return`Cri de guerre : +${effect.value??1} attaque à une unité alliée.`;case'summon':return`Cri de guerre : invoque une unité ${effect.target??''}.`;case'board_wipe':return'Détruit toutes les unités adverses.';default:return'Aucun effet spécial.';}}

const PLANNED_MYTHICS: CardDef[] = [
  { id:'mythique-loup-du-nexus', name:'Loup du Nexus', faction:'Meute', level:1, type:'unit', cost:5, attack:8, health:8, effect:{kind:'buff',value:2}, copies:1, rarity:'Mythique', boosterOnly:true, image:`${import.meta.env.BASE_URL}cards/mythique-loup-du-nexus.png`, text:'Mythique — présence légendaire de la Meute. Limitée à 1 exemplaire par deck.' },
  { id:'mythique-paladin-du-nexus', name:'Paladin du Nexus', faction:'Chevalier', level:1, type:'unit', cost:5, attack:7, health:10, effect:{kind:'protect'}, copies:1, rarity:'Mythique', boosterOnly:true, image:`${import.meta.env.BASE_URL}cards/mythique-paladin-du-nexus.png`, text:'Mythique — rempart absolu de l’ordre. Limitée à 1 exemplaire par deck.' },
  { id:'mythique-seigneur-de-guerre', name:'Seigneur de Guerre Mythique', faction:'Orc', level:1, type:'unit', cost:5, attack:9, health:7, effect:{kind:'damage',value:3}, copies:1, rarity:'Mythique', boosterOnly:true, image:`${import.meta.env.BASE_URL}cards/mythique-seigneur-de-guerre.png`, text:'Mythique — incarnation ultime de la Fureur Sauvage. Limitée à 1 exemplaire par deck.' },
  { id:'mythique-dragon-du-nexus', name:'Dragon du Nexus', faction:'Dragon', level:1, type:'unit', cost:6, attack:11, health:11, effect:{kind:'damage',value:4}, flying:true, attackDelayTurns:2, copies:1, rarity:'Mythique', boosterOnly:true, image:`${import.meta.env.BASE_URL}cards/mythique-dragon-du-nexus.png`, text:'Mythique — titan volant à Inertie Draconique. Limitée à 1 exemplaire par deck.' },
  { id:'mythique-roi-gobelin', name:'Roi Gobelin du Nexus', faction:'Gobelin', level:1, type:'unit', cost:4, attack:6, health:5, effect:{kind:'summon',target:'Gobelin'}, blitz:true, copies:1, rarity:'Mythique', boosterOnly:true, image:`${import.meta.env.BASE_URL}cards/mythique-roi-gobelin.png`, text:'Mythique — mène immédiatement la Ruée de la Horde. Blitz. Limitée à 1 exemplaire par deck.' },
];

export const CARDS:CardDef[]=[...buildFaction('Meute',wolfRows),...buildFaction('Chevalier',knightRows),...buildFaction('Orc',orcRows),...buildFaction('Dragon',dragonRows),...buildFaction('Gobelin',goblinRows)].map((card)=>{const baseId=card.evolvesFrom??card.id;if(card.faction==='Dragon')return {...card,flying:PLANNED_FLYING_IDS.has(baseId)||undefined};if(card.faction==='Gobelin')return {...card,blitz:card.type==='unit'?true:card.blitz};return card;}).concat(PLANNED_MYTHICS);
assertValidCardDatabase(CARDS);
export const CARD_DB:Map<string,CardDef>=new Map(CARDS.map(c=>[c.id,c]));
export function getCard(id:string):CardDef{const card=CARD_DB.get(id);if(!card)throw new Error(`Carte inconnue : ${id}`);return card;}
export function cardsByFaction(faction:Faction):CardDef[]{return CARDS.filter(c=>c.faction===faction);}
export function starterDeck(faction:Faction):string[]{const level1=cardsByFaction(faction).filter(c=>c.level===1&&!c.boosterOnly&&!c.assetMissing);const deck:string[]=[];for(const card of level1)for(let i=0;i<2;i++)deck.push(card.id);return deck;}
