import type { CombatTrigger, StoryCharacterId } from './types';

/** Répliques contextuelles courtes. Le lecteur de banter choisit une variante
 * et applique son cooldown ; aucune réplique ne porte de logique de combat. */
export const COMBAT_BANTER: Partial<Record<StoryCharacterId, Partial<Record<CombatTrigger, string[]>>>> = {
  lyra: {
    first_summon:['Ton fragment réagit à tes pensées. Donne-lui un ordre.','Ne force pas le Nexus. Écoute-le.'],
    first_damage:['Bien. Maintenant regarde comment ton adversaire répond.'],
    big_damage:['Ça, même la forêt l’a senti.'],
    player_low_hp:['Tu es encore debout. Alors le duel n’est pas fini.'],
    enemy_low_hp:['La piste se referme. Termine proprement.'],
    evolution:['Attends. Cette résonance ne devrait pas être possible.','Encore cette lumière… Qui t’a appris à faire ça ?'],
    mythic_summon:['Le Nexus vient de changer de rythme.'],
    direct_attack:['L’impact traverse tout le terrain.'],
    board_wipe:['Plus rien ne bouge… pour l’instant.'],
    victory:['D’accord. Je commence à comprendre pourquoi le fragment t’a choisi.'],
    defeat:['Relève-toi. J’ai encore beaucoup trop de questions.'],
  },
  kael: {
    first_summon:['Formation propre. Ne la gaspille pas.'],
    first_damage:['Premier sang. Maintenant commence le vrai duel.'],
    big_damage:['Je t’ai sous-estimé.'],
    player_low_hp:['Tu peux encore abandonner avec honneur.'],
    enemy_low_hp:['Très bien. Plus besoin de retenir mes coups.'],
    evolution:['Encore… Cette résonance n’est pas normale.'],
    mythic_summon:['Si les Archives ont caché cela, qu’ont-elles caché d’autre ?'],
    direct_attack:['La ligne est ouverte. Une erreur coûte cher.'],
    board_wipe:['Toute la formation… balayée.'],
    victory:['Victoire méritée. Je n’accorde pas ce compliment souvent.'],
    defeat:['Cette manche est à toi. Pas mes convictions.'],
  },
  gribz: {
    first_summon:['La quantité est une forme de qualité !'],
    first_damage:['HA ! C’était calibré. À peu près.'],
    big_damage:['Ouh. Ça, j’aurais dû le breveter.'],
    player_low_hp:['Techniquement, tant qu’il te reste un point de vie, mon plan fonctionne.'],
    enemy_low_hp:['Je propose qu’on appelle ça une victoire scientifique imminente.'],
    evolution:['Ohhh. Ça brille ET ça devient plus dangereux. J’adore.'],
    mythic_summon:['Bon. Ça, même moi je vais éviter de démonter pour voir dedans.'],
    direct_attack:['TOUCHÉ ! Le sol aussi, apparemment.'],
    board_wipe:["J'commence à manquer de remplaçables."],
    victory:['Victoire parfaitement planifiée ! Ne vérifie surtout pas mes notes.'],
    defeat:['Ça devait faire ça. Enfin, presque.'],
  },
  rakh: {
    first_summon:['Montre-moi si tu commandes… ou si tu espères.'],
    first_damage:['Un vrai coup. Enfin.'],
    big_damage:['Voilà une force que je peux respecter.'],
    player_low_hp:['La douleur ne décide rien. Ta prochaine décision, oui.'],
    enemy_low_hp:['C’est maintenant que commence la partie intéressante.'],
    evolution:['Le fragment t’obéit sans te dévorer… intéressant.'],
    mythic_summon:['Même les tambours se sont tus.'],
    direct_attack:['Le terrain garde la cicatrice. Moi aussi.'],
    board_wipe:['Plus de lignes. Plus d’excuses.'],
    victory:['La force sans lucidité ne vaut rien. Tu as montré les deux.'],
    defeat:['Mémorise cette victoire. La prochaine te coûtera davantage.'],
  },
  vaeloryx: {
    first_summon:['Tu appelles ces créatures comme les Liés d’autrefois.'],
    first_damage:['Chaque choc réveille un souvenir sous cette pierre.'],
    big_damage:['Oui… cette puissance-là, je m’en souviens.'],
    player_low_hp:['Ton corps faiblit. Ta résonance, elle, grandit.'],
    enemy_low_hp:['Tu approches d’une victoire dont tu ignores encore le prix.'],
    evolution:['Cette lumière… je ne l’avais pas vue depuis la Fracture.'],
    mythic_summon:['Silence. Quelque chose, derrière le Nexus, vient de t’entendre.'],
    direct_attack:['La pierre se fissure. Elle se souviendra de toi.'],
    board_wipe:['La Fracture aussi commença par un silence après la lumière.'],
    victory:['Un Lié… après tout ce temps.'],
    defeat:['Tu n’étais pas prêt pour la vérité. Peut-être est-ce une chance.'],
  },
  morvane: {
    first_summon:['Les morts reconnaissent ceux qui n’ont pas encore oublié leur nom.'],
    first_damage:['La douleur passe. La mémoire reste.'],
    big_damage:['Voilà un coup que même les tombeaux raconteront.'],
    player_low_hp:['Tu comprends maintenant pourquoi certains refusent de mourir oubliés.'],
    enemy_low_hp:['Ne confonds pas silence et défaite, Lié.'],
    evolution:['Le Nexus se souvient de cette forme… moi aussi.'],
    mythic_summon:['Ce nom existait avant que votre royaume n’apprenne à mentir.'],
    direct_attack:['Une nouvelle fissure. Un nouveau souvenir.'],
    board_wipe:['Tout tombe. C’est ce qui reste après qui compte.'],
    victory:['Alors écoute. Les Sans-Nom vont enfin parler.'],
    defeat:['Même battus, nous ne retournerons plus dans l’oubli.'],
  },
};
