import{useState}from'react';import{NavLink,Route,Routes,useNavigate}from'react-router-dom';import{motion}from'framer-motion';import{cards,Card}from'./data/cards';import{useGame}from'./store/game';import wolfArt from'./assets/cards/loup-alpha.png';import paladinArt from'./assets/cards/paladin-royaume.png';import cardBack from'./assets/cards/nexus-card-back.png';
const nav=['Jouer','Collection','Decks','Profil','Classement','Boutique','Tutoriel','Paramètres'];const path=(x:string)=>x==='Jouer'?'/':'/'+x.toLowerCase();
function Shell({children}:{children:React.ReactNode}){return <><aside><h1>✦ NEXUS <small>CARD ARENA</small></h1>{nav.map(x=><NavLink key={x} to={path(x)} end={x==='Jouer'}>{x}</NavLink>)}</aside><main>{children}</main></>}
const CardView=({card,onClick}:{card:Card,onClick?:()=>void})=>{const name=card.name.toLowerCase();const image=name.includes('loup')?wolfArt:name.includes('paladin')?paladinArt:cardBack;return <motion.button whileHover={{y:-8,rotate:1}} className={'card '+card.rarity} onClick={onClick}><i>{card.faction}</i><b>{card.name}</b><strong className="card-art" style={{backgroundImage:`url(${image})`}}>{name.includes('loup')||name.includes('paladin')?'':card.art}</strong><p>{card.text}</p><footer><span>{card.cost} ◆</span><span>⚔ {card.attack}　♥ {card.health}</span></footer></motion.button>};
function Home(){const go=useNavigate();const s=useGame();return <section className="home"><p className="eyebrow">LE SERMENT ET LA MEUTE</p><h2>Entre dans<br/><em>l’Évosphère</em></h2><p>Construis ton héritage et affronte les gardiens de Nexus.</p><button className="primary" onClick={()=>go('/combat')}>⚔ Jouer contre l’IA</button><div className="stats"><b>Niveau {s.level}</b><span>{s.wins} victoires · {s.losses} défaites</span><span>{s.gold} ✦</span></div></section>}
function Collection(){const[query,setQuery]=useState('');const owned=useGame(s=>s.owned);return <section><h2>Collection</h2><input placeholder="Rechercher une carte…" value={query} onChange={e=>setQuery(e.target.value)}/><div className="grid">{cards.filter(c=>c.name.toLowerCase().includes(query.toLowerCase())).map(c=><CardView key={c.id} card={c}/>)}</div><p className="hint">{owned.length}/{cards.length} cartes possédées</p></section>}
function Decks(){const s=useGame();const add=(id:string)=>s.deck.length<40&&s.saveDeck([...s.deck,id]);return <section><h2>Constructeur de decks</h2><p className="hint">{s.deck.length}/40 cartes · maximum 3 exemplaires</p><div className="builder"><div><h3>Deck Chronos</h3>{s.deck.map((id,i)=><button className="deck-row" key={i} onClick={()=>s.saveDeck(s.deck.filter((_,n)=>n!==i))}>{cards.find(c=>c.id===id)?.name} <span>×</span></button>)}</div><div className="grid">{cards.map(c=><CardView key={c.id} card={c} onClick={()=>add(c.id)}/>)}</div></div></section>}
function Zone({title,count,icon}:{title:string;count:number;icon:string}){return <div className="zone-wrap"><b>{title}</b><div className={'board slots-'+count}>{Array.from({length:count},(_,i)=><div key={i}>{icon}</div>)}</div></div>};function Combat(){const[hp,setHp]=useState([30,30]);const[mana,setMana]=useState(3);const[hand,setHand]=useState(cards.slice(0,4));const s=useGame();const play=(c:Card)=>{if(c.cost>mana)return;const enemy=hp[1]-c.attack;if(enemy<=0){setHp([hp[0],0]);s.record(true)}else{setHp([Math.max(0,hp[0]-(2+Math.floor(Math.random()*4))),enemy]);setMana(mana-c.cost)};setHand(hand.filter(x=>x.id!==c.id))};return <section className="battle"><h2>La Sentinelle <span>♥ {hp[1]}/30</span></h2><div className="battle-meta"><span>Évosphères · Extra deck</span><span>Fosse · Cimetière</span></div><Zone title="Zones de créatures" count={3} icon="♜"/><Zone title="Enchantements & sortilèges" count={5} icon="✧"/><p>Mana {mana}/3 · Jouez une carte puis l’IA riposte.</p><div className="hand">{hand.map(c=><CardView key={c.id} card={c} onClick={()=>play(c)}/>)}</div><h3>CHRONOS <span>♥ {hp[0]}/30</span></h3><div className="battle-meta"><span>Fosse · Cimetière</span><span>Évosphères · Extra deck</span></div><Zone title="Enchantements & sortilèges" count={5} icon="✧"/><Zone title="Zones de créatures" count={3} icon="♜"/>{hp[0]===0&&<p className="loss">Défaite — relancez un combat.</p>}{hp[1]===0&&<p className="win">Victoire ! Récompense obtenue.</p>}</section>}
function Profile(){const s=useGame();return <section><h2>Profil de Chronos</h2><div className="profile"><b>✦</b><div><h3>Chronos</h3><p>Niveau {s.level} · {s.wins} victoires · {s.losses} défaites</p><progress value={s.wins%10} max="10"/></div></div></section>};function Simple({title}:{title:string}){return <section><h2>{title}</h2><p className="hint">Cette section est prête à être enrichie. Les données sont sauvegardées localement.</p></section>}
export default function App(){return <Shell><Routes><Route path="/" element={<Home/>}/><Route path="/collection" element={<Collection/>}/><Route path="/decks" element={<Decks/>}/><Route path="/profil" element={<Profile/>}/><Route path="/combat" element={<Combat/>}/>{['classement','boutique','tutoriel','paramètres'].map(x=><Route key={x} path={'/'+x} element={<Simple title={x[0].toUpperCase()+x.slice(1)}/>}/>)}</Routes></Shell>}
