import React from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, HashRouter, useLocation } from 'react-router-dom';
import { Capacitor } from '@capacitor/core';
import App from './App';
import { FactionUnlockShop } from './components/FactionUnlockShop';
import BattlePass from './components/BattlePass';
import HomeProfileBadge from './components/HomeProfileBadge';
import BattleQuickSettings from './components/BattleQuickSettings';
import FirstRunTutorial from './components/FirstRunTutorial';
import CombatPlaylistController from './components/CombatPlaylistController';
import { installFactionUnlockRules } from './progression/faction-unlocks';
import './styles.css';
import './arena.css';
import './mobile-fixes.css';
import './faction-vfx.css';
import './cinematics.css';
import './faction-unlocks.css';
import './battle-pass.css';
import './ui-polish.css';
import './visual-overhaul.css';
import './profile-account.css';
import './battle-ui-polish.css';
import './battle-polish.css';
import './fantasy-frames.css';
import './generated-frame-assets.css';

const frameAsset = (name: string) => `url("${import.meta.env.BASE_URL}ui/frames/${name}.webp")`;
document.documentElement.style.setProperty('--frame-panel-nexus', frameAsset('panel-nexus'));
document.documentElement.style.setProperty('--frame-panel-meute', frameAsset('panel-meute'));
document.documentElement.style.setProperty('--frame-panel-chevalier', frameAsset('panel-chevalier'));
document.documentElement.style.setProperty('--frame-panel-orc', frameAsset('panel-orc'));
document.documentElement.style.setProperty('--frame-panel-dragon', frameAsset('panel-dragon'));
document.documentElement.style.setProperty('--frame-panel-gobelin', frameAsset('panel-gobelin'));
document.documentElement.style.setProperty('--frame-panel-squelette', frameAsset('panel-squelette'));
document.documentElement.style.setProperty('--frame-button-nexus', frameAsset('button-nexus'));

const isInteractiveGameElement = (target: EventTarget | null) => target instanceof Element && Boolean(target.closest('#root button, #root a, #root .card, #root .field-card, #root .field-unit, #root .menu-card, #root .card-pile, #root img'));
document.addEventListener('contextmenu',event=>{if(isInteractiveGameElement(event.target))event.preventDefault()});
document.addEventListener('dragstart',event=>{if(isInteractiveGameElement(event.target))event.preventDefault()});
document.addEventListener('selectstart',event=>{const target=event.target;if(!(target instanceof Element))return;if(target.closest('input, textarea, [contenteditable="true"]'))return;if(target.closest('#root'))event.preventDefault()});
function PlayBattlePass(){const location=useLocation();return location.pathname==='/'?<BattlePass/>:null}
installFactionUnlockRules();
const Router = __USE_HASH_ROUTER__ ? HashRouter : BrowserRouter;
const routerProps = __USE_HASH_ROUTER__ ? {} : { basename: import.meta.env.BASE_URL };
createRoot(document.getElementById('root')!).render(<React.StrictMode><Router {...routerProps}><App/><FactionUnlockShop/><HomeProfileBadge/><BattleQuickSettings/><FirstRunTutorial/><CombatPlaylistController/><PlayBattlePass/></Router></React.StrictMode>);
if('serviceWorker'in navigator&&!Capacitor.isNativePlatform())window.addEventListener('load',()=>{navigator.serviceWorker.register(`${import.meta.env.BASE_URL}sw.js`).catch(()=>{})});
